[platformio]
boards_dir = boards

[env:T5_E_PAPER_S3_V7]
platform = espressif32@6.5.0
board = T5-ePaper-S3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DDISABLE_ALL_LIBRARY_WARNINGS
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=5
  -DBOARD_HAS_PSRAM
  -DPSRAM_SPEED=120MHz
  -DT5_FIELD_OS=1
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  mikalhart/TinyGPSPlus@^1.1.0
  jgromes/RadioLib@^7.0.2
  h2zero/NimBLE-Arduino@^1.4.2
  links2004/WebSockets@^2.4.1


[env:T5_E_PAPER_S3_V7_test]
extends = env:T5_E_PAPER_S3_V7
test_build_src = true
