[env:lilygo_t5_s3_pro]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM
  -DT5_FIELD_OS=1
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  mikalhart/TinyGPSPlus@^1.1.0
  jgromes/RadioLib@^7.0.2
  h2zero/NimBLE-Arduino@^1.4.2
  links2004/WebSockets@^2.4.1


[env:lilygo_t5_s3_pro_test]
extends = env:lilygo_t5_s3_pro
test_build_src = true
