#if defined(ARDUINO) && !defined(PAPERGO_DISABLE_EMBEDDED_EPDIY)
extern "C" {
#include "../lib/epdiy/src/epdiy.c"
#include "../lib/epdiy/src/render.c"
#include "../lib/epdiy/src/output_lcd/render_lcd.c"
#include "../lib/epdiy/src/output_lcd/lcd_driver.c"
#include "../lib/epdiy/src/output_i2s/render_i2s.c"
#include "../lib/epdiy/src/output_i2s/rmt_pulse.c"
#include "../lib/epdiy/src/output_i2s/i2s_data_bus.c"
#include "../lib/epdiy/src/output_common/lut.c"
#include "../lib/epdiy/src/output_common/line_queue.c"
#include "../lib/epdiy/src/output_common/render_context.c"
#include "../lib/epdiy/src/font.c"
#include "../lib/epdiy/src/displays.c"
#include "../lib/epdiy/src/board_specific.c"
#include "../lib/epdiy/src/builtin_waveforms.c"
#include "../lib/epdiy/src/highlevel.c"
#include "../lib/epdiy/src/board/tps65185.c"
#include "../lib/epdiy/src/board/pca9555.c"
#include "../lib/epdiy/src/board/epd_board.c"
#include "../lib/epdiy/src/board/epd_board_common.c"
#include "../lib/epdiy/src/board/epd_board_lilygo_t5_47.c"
#include "../lib/epdiy/src/board/epd_board_v2_v3.c"
#include "../lib/epdiy/src/board/epd_board_v4.c"
#include "../lib/epdiy/src/board/epd_board_v5.c"
#include "../lib/epdiy/src/board/epd_board_v6.c"
#include "../lib/epdiy/src/board/epd_board_v7.c"
}
#endif
